# Generated by Django 5.1.3 on 2024-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gsm', models.BooleanField()),
                ('umts', models.BooleanField()),
                ('lte', models.BooleanField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
