# Generated by Django 5.1.3 on 2024-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='gsm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='lte',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='umts',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
